image: node:latest # can be upgraded, depending on your node version used

cache:
  paths:
    - node_modules/

deploy:
  stage: deploy
  script:
    - npm install
    - CI=false
    - npm run build
    - apt-get update -qq && apt-get install -y -qq lftp
    - lftp -c "set ftp:ssl-allow no; open -u $ftp_username,$ftp_password $ftp_host; mirror -Rnev ./build/ ./panel --parallel=5"
  artifacts:
    paths:
      - public # mandatory, other folder won't work