image: node:latest # can be upgraded, depending on your node version used

cache:
  paths:
    - node_modules/

deploy:
  stage: deploy
  script:
    - npm install
    - CI=false
    - npm run build
    - rm -rf public
    - mv build public
    - apt-get update -qq && apt-get install -y -qq lftp
    - lftp -c "set ftp:ssl-allow no; open -u $ftp_username,$ftp_password $ftp_host; mirror -Rnev ./ ./panel --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"
  artifacts:
    paths:
      - public # mandatory, other folder won't work
  only:
    - master # or dev, the branch you want to publish